services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: "db1,db2,db3"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgscript/init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
      - ./pgscript/max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    ports:
      - '5442:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '80:80'
    depends_on:
      - db

